### ISSUE TITLE
how to cover a layer on tabar in child Component?

### ISSUE THREAD

**Issue by ghost** [exponentjs/react-native-tab-navigator#113]
Hi.

I need cover a layer on whole screen, this is the style code

`position: 'absolute',
    zIndex: 100,
    left: 0,
    right: 0,
    top: 0,
    backgroundColor: 'rgba(0,0,0,0.4)',
    height: common.window.height,`

but, i find the tabbar on the top of the layer, how i can cover the layer on the top of the tabbar?

thank!

**Comment by ide** [comment]
You can't do this with child components, you need to write your code like this:

``` js
<View>
  <TabNavigator />
  <LayerView style={{ position: 'absolute' }} />
</View>
```
