### ISSUE TITLE
Tab bar without title

### ISSUE THREAD

**Issue by Fantasim** [exponentjs/react-native-tab-navigator#115]
Hi,

How can i set any title in my items on react-native-tab-navigator ??

like that : 
http://www.yagoshack.fr/?v=capturvzv.png

**Comment by ide** [comment]
Have you tried setting the title and titleStyle props to hide the titles?

**Comment by Fantasim** [comment]
Yes i've add opacity 0 on title and top: 5 on icon, it looks like what I imagined
