### ISSUE TITLE
how to set icon?

### ISSUE THREAD

**Issue by ghost** [exponentjs/react-native-tab-navigator#118]
Hi, I can´t set an icon for each tab this is my code:

  <TabNavigator.Item
          selected={this.state.selectedTab === 'dashboard'}
          title="Dashboard"
          renderIcon={() => \<Image source={{uri: iconDashboard}} />}
          renderSelectedIcon={() => \<Image source={{uri: iconDashboard}} />}
          onPress={() => this.setState({ selectedTab: 'dashboard' })}>
          <Dashboard  navigator={this.props.navigator}></Dashboard>
        </TabNavigator.Item>
Any help?

**Comment by kadzier** [comment]
Having this exact same issue too my image definitely exists and can be displayed elsewhere but when I set it inside renderIcon{} and renderSelectedIcon{} it still shows blank for that tab.

**Comment by kadzier** [comment]
Just figured this one out... you have to actually return the <Image> element in your function, using the return() keyword. 

So changing my function to:

renderIcon = {() => {
    return( < Image source={...}  / > )
}}

worked for me.
