### ISSUE TITLE
plase add tabSelectedStyle

### ISSUE THREAD

**Issue by zhuzhiyuan** [exponentjs/react-native-tab-navigator#120]
i wont to update Selected tab backgroundColor,but no the popos

**Comment by footprint** [comment]
![111](https://cloud.githubusercontent.com/assets/1246678/21846739/7897372e-d833-11e6-851d-92c9278130b3.png)

it looks like this!

**Comment by zhuzhiyuan** [comment]
yes ,how did you do it?

**Comment by zhuzhiyuan** [comment]
@footprint ,yes ,how did you do it?
