### ISSUE TITLE
badgeText styling is off, text is behind title

### ISSUE THREAD

**Issue by jaredmharris** [exponentjs/react-native-tab-navigator#123]
Attached screenshot showing how the badge text does not appear properly at bottom of screen.

![screen shot 2017-01-10 at 9 43 31 pm](https://cloud.githubusercontent.com/assets/1580419/21833092/e05fd4bc-d77d-11e6-8e5d-7bb703667ccc.png)

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
