### ISSUE TITLE
raact-native 0.41 use android:nodes Click on the page has been clicked to report the error

### ISSUE THREAD

**Issue by x4922** [exponentjs/react-native-tab-navigator#127]
raact-native 0.41 use android:nodes Click on the page has been clicked to report the error:error while updating property 'removeClippedSubviews' of a ciew managed by : RCTView
![Uploading image.png…]()

**Comment by ptomasroos** [comment]
This issue is very incomplete, feel free to open a new one with working image and error description if its still happens
