### ISSUE TITLE
How to change the color of selected tab title? 

### ISSUE THREAD

**Issue by DavidKongDesheng** [exponentjs/react-native-tab-navigator#128]
<Tab
          selected={selectedTab === Strings.FEED}
          title={Strings.FEED}
          titleStyle={[
            styles.titleStyle,
            selectedTab === Strings.FEED && styles.titleSelectedStyle
          ]}
          tabStyle={styles.tabStyle}
...

**Comment by skv-headless** [comment]
Have you tried `selectedTitleStyle`?

**Comment by DavidKongDesheng** [comment]
My bad, didn't see that property....Thanks bro.
