### ISSUE TITLE
undefined is not an object(evaluating 'item.props.selected')

### ISSUE THREAD

**Issue by UniqHu** [exponentjs/react-native-tab-navigator#129]
always appears error message -------undefined is not an object(evaluating 'item.props.selected').
refers to TabNavigator.js:58

**Comment by manhhp** [comment]
I get the same error, someone help me out?

undefined is not an object (evaluating 'item.props.selected')
<unknown>
    C:\projects\myapp\node_modules\react-native-tab-navigator\TabNavigator.js:58:46
forEachSingleChild
    C:\projects\myapp\node_modules\react\lib\ReactChildren.js:51:12
traverseAllChildrenImpl
    C:\projects\myapp\node_modules\react\lib\traverseAllChildren.js:77:13
traverseAllChildrenImpl
    C:\projects\myapp\node_modules\react\lib\traverseAllChildren.js:93:46
traverseAllChildren
    C:\projects\myapp\node_modules\react\lib\traverseAllChildren.js:172:33
forEachChildren
    C:\projects\myapp\node_modules\react\lib\ReactChildren.js:71:22
_updateRenderedSceneKeys
    C:\projects\myapp\node_modules\react-native-tab-navigator\TabNavigator.js:53:27
TabNavigator
    C:\projects\myapp\node_modules\react-native-tab-navigator\TabNavigator.js:31:55
<unknown>
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:405:30
measureLifeCyclePerf
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:85:11
_constructComponentWithoutOwner
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:405:10
_constructComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:376:10
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:202:6
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
mountChildren
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:264:10
initializeChildren
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeBaseComponent.js:74:41
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeBaseComponent.js:212:6
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
mountChildren
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:264:10
initializeChildren
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeBaseComponent.js:74:41
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeBaseComponent.js:212:6
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
performInitialMount
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:496:6
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:346:40
mountComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:62:6
updateChildren
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactChildReconciler.js:157:10
_reconcilerUpdateChildren
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:212:10
_updateChildren
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:345:6
updateChildren
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:331:25
receiveComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeBaseComponent.js:130:24
receiveComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:163:38
_updateRenderedComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:982:8
_performComponentUpdate
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:944:34
updateComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:847:8
receiveComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:710:6
receiveComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:163:38
updateChildren
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactChildReconciler.js:143:10
_reconcilerUpdateChildren
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:212:10
_updateChildren
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:345:6
updateChildren
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactMultiChild.js:331:25
receiveComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeBaseComponent.js:130:24
receiveComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:163:38
_updateRenderedComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:982:8
_performComponentUpdate
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:944:34
updateComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:847:8
receiveComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:710:6
receiveComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:163:38
_updateRenderedComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:982:8
_performComponentUpdate
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:944:34
updateComponent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:847:8
performUpdateIfNecessary
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactCompositeComponent.js:735:8
performUpdateIfNecessary
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactReconciler.js:213:46
runBatchedUpdates
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactUpdates.js:171:6
perform
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\utils\Transaction.js:149:24
perform
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\utils\Transaction.js:149:24
perform
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactUpdates.js:96:8
flushBatchedUpdates
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactUpdates.js:199:26
closeAll
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\utils\Transaction.js:222:29
perform
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\utils\Transaction.js:163:24
batchedUpdates
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactDefaultBatchingStrategy.js:65:33
batchedUpdates
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\shared\stack\reconciler\ReactUpdates.js:111:41
_receiveRootNodeIDEvent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeEventEmitter.js:126:32
receiveEvent
    C:\projects\myapp\node_modules\react-native\Libraries\Renderer\src\renderers\native\ReactNativeEventEmitter.js:150:6
__callFunction
    C:\projects\myapp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:242:47
<unknown>
    C:\projects\myapp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:108:26
guard
    C:\projects\myapp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:46:4
callFunctionReturnFlushedQueue
    C:\projects\myapp\node_modules\react-native\Libraries\BatchedBridge\MessageQueue.js:107:10

**Comment by jaumebosch** [comment]
Copying the example also gives me this error, any clue?

**Comment by mesutyigit** [comment]
Did you solve. I've same issue

**Comment by bastyen** [comment]
Maybe you just copy paste some code (like the native elements example). 
So just remove the comment /* ... more tabs here */. Should works after that.

**Comment by GFWNB** [comment]
I got the same error!

and do you resolve it?

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
