### ISSUE TITLE
Tab cover the bottom of the listView

### ISSUE THREAD

**Issue by Germinate** [exponentjs/react-native-tab-navigator#132]
Here is my issue. When the listView of the childView longer than one screen, and you scroll to the end, the tab cover the bottom. Any one can help me?
![screenshot_2017-03-03-09-43-26](https://cloud.githubusercontent.com/assets/3623729/23535239/1d50ddec-fff8-11e6-96a6-69ad0698799f.jpeg)

**Comment by zhenyu-dev** [comment]
style you wrapper component with paddingBottom: [your item height]

**Comment by ptomasroos** [comment]
What @li-zhenyu proposed ^
