### ISSUE TITLE
Inactive tabs are not unmounted

### ISSUE THREAD

**Issue by gperdomor** [exponentjs/react-native-tab-navigator#133]
Hi...

I notice that inactive tabs are still mounted, exist any way to prevent that?...

**Comment by ide** [comment]
You would have to write the unmounting logic yourself if you want this behavior.

**Comment by gperdomor** [comment]
@ide can you explain? please leave the issue open, so other devs can help and give ideas

**Comment by ide** [comment]
The issue is closed because this component makes an explicit choice not to do this. You can unmount your inactive scene contents however you want -- this component doesn't stop you from doing this, but it also doesn't come with a way to do so.
