### ISSUE TITLE
how to uninstall tab-navigator when i unload

### ISSUE THREAD

**Issue by thiswhy** [exponentjs/react-native-tab-navigator#135]
Hi man!
      I want to change user,so I go back to login,but tab-navigator doesn't uninstall ,so when I had login to tab-navigator pager,there are two tab-navigator component waiting for me ~~~hooly shit! 
     How to solve this problem,online for waiting.....worry!
My english is poor ,i'm sorry for wrony words.

**Comment by thiswhy** [comment]
thank you!I have an other way to save this question,just hide this tab in children view

**Comment by ptomasroos** [comment]
Make sure you only render one tab-navigator at a time sounds like the solution here, set a state variable when you're signed in and one when you're signed out. And depending on which state you're in draw either one of them. Sometimes you need to make sure to set a key on the element to avoid reuse. (applies to all components)
