### ISSUE TITLE
creating two tab navigators is splitting the screen

### ISSUE THREAD

**Issue by ahmdsdk** [exponentjs/react-native-tab-navigator#136]
I am creating an app with two TabNavigators one at the top and one at the bottom.. but When I do that, the selected tab view is not taking the full screen rather than the screen is getting divided horizontally. where the bottom screen corresponds to the bottom TabNavigator and the top screen relates to the top TabNavigator.. is there a way to solve this issue?

**Comment by ide** [comment]
TabNavigator was designed to support just one tab bar at a time. You could try nesting the TabNavigators -- in your root component have TabNavigator 1, and then in a tab item's screen you'd put Tab Navigator 2.

**Comment by ahmdsdk** [comment]
But that would mean Tab navigator 2 won't show up unless that tab item which includes the Tab navigator 2 is selected, right?

**Comment by ide** [comment]
Yeah. If you want both tabs to always be present on the screen you should fork this component or write your own.

**Comment by ElSadeq** [comment]
What if I put the 2nd Tab navigator in all the screens of the first Tab navigator items? Would that work?

**Comment by ptomasroos** [comment]
Will close this as its not in the goals for this library to provide.
