### ISSUE TITLE
React native tab navigator not work

### ISSUE THREAD

**Issue by farrukhbashir** [exponentjs/react-native-tab-navigator#142]
sir in tab navigator there no index.android.js file then which one run on first and it is code for ios  and in react native android how it is working

**Comment by farrukhbashir** [comment]
![screenshot_2017-04-19-11-44-46](https://cloud.githubusercontent.com/assets/22269001/25175417/88c26f38-24af-11e7-8ce6-3d634716e74e.png)
this is the error pic

**Comment by ptomasroos** [comment]
Hi there! The documentation is in the README.md, we'll try to provide a example on how to integrate it soon
