### ISSUE TITLE
Collapsing ToolBar with TabBar

### ISSUE THREAD

**Issue by ashrithks** [exponentjs/react-native-tab-navigator#146]
Hi All,

Tried to achieve collapsing toolbar with tabbar,

 -- ![Valid XHTML](https://camo.githubusercontent.com/97497a24719b85f5d618cba66ac4d23ccfdd7023/687474703a2f2f692e696d6775722e636f6d2f615069333243712e676966)

referring to --  https://medium.com/appandflow/react-native-scrollview-animated-header-10a18cb9469e

But no luck!!!
![ezgif com-video-to-gif 1](https://cloud.githubusercontent.com/assets/19853363/26247388/49bb73c4-3cbb-11e7-8560-de277e711796.gif)

**Comment by ptomasroos** [comment]
Hey ! Could you please explain what the issue is here? Your description does not really give me a context how to help you out or if there's a bug to be fixed

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
