### ISSUE TITLE
install fail

### ISSUE THREAD

**Issue by Allansk2** [exponentjs/react-native-tab-navigator#151]
I'm in my React Native project directory and run:
npm install react-native-tab-navigator --save
get 

npm WARN gentlyRm not removing /Users/....../node_modules/.bin/jest as it wasn't installed by /Users/...../node_modules/jest-cli
npm notice created a lockfile as package-lock.json. You should commit this file.
+ react-native-tab-navigator@0.3.3
added 2 packages and removed 641 packages in 21.324s

It seem to remove some of other packages and then I can't build my ios project. What am I missing?

my package.json
{
	"name": "xxx",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"start": "node node_modules/react-native/local-cli/cli.js start",
		"test": "jest"
	},
	"dependencies": {
		"react": "16.0.0-alpha.12",
		"react-native": "0.45.1"
	},
	"devDependencies": {
		"babel-jest": "20.0.3",
		"babel-preset-react-native": "2.0.0",
		"jest": "20.0.4",
		"react-test-renderer": "16.0.0-alpha.12"
	},
	"jest": {
		"preset": "react-native"
	}
}

**Comment by AndroidKiven** [comment]
I have the same question too

**Comment by MasterShu** [comment]
maybe you can use command
` yarn add  react-native-tab-navigator`

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
