### ISSUE TITLE
Element type is invalid: expected a string (for built-in components) or a class/function (for composite components) but got: object.  Check the render method of TabNavigator

### ISSUE THREAD

**Issue by devanshsadhotra** [exponentjs/react-native-tab-navigator#153]
```<TabNavigator>
  <TabNavigator.Item
    selected={this.state.selectedTab === 'home'}
    title="Home"
    renderIcon={() => <Image source={...} />}
    renderSelectedIcon={() => <Image source={...} />}
    badgeText="1"
    onPress={() => this.setState({ selectedTab: 'home' })}>
    {homeView}
  </TabNavigator.Item>
  <TabNavigator.Item
    selected={this.state.selectedTab === 'profile'}
    title="Profile"
    renderIcon={() => <Image source={...} />}
    renderSelectedIcon={() => <Image source={...} />}
    renderBadge={() => <CustomBadgeView />}
    onPress={() => this.setState({ selectedTab: 'profile' })}>
    {profileView}
  </TabNavigator.Item>
</TabNavigator>```

i am implementing as mentioned above , but it's showing me error as mentioned in heading . 
 Kindly help

**Comment by devanshsadhotra** [comment]
i just figured out , it's showing me issue in render Icon in both tab items. and when now i remove render Icon and render selected icon , its throwing me , this error : 
`react children only expected to receive a single react element child`

**Comment by devanshsadhotra** [comment]
Another thing !! i am not been able to view my component

**Comment by devanshsadhotra** [comment]
I am not been able to select tabs after clicking over those.

**Comment by guilhermemello** [comment]
Same message here :(

**Comment by devanshsadhotra** [comment]
i have faced 1 more issue, i am not been able to navigate from any of the tabs to other page. 
for eg. i have a name list in one of my tab. and after clicking on that name i need to go to the profile. but navigation is just not working

**Comment by devanshsadhotra** [comment]
Is there anyone from the community , who can help me solve these issues? @ptomasroos

**Comment by vokhuyet** [comment]
hey, change both {homeView}and {profileView} to {<homeView />} and {<profileVIew />}
 fixed for me

**Comment by vokhuyet** [comment]
`<homeView /> and <profileView/>`

**Comment by vokhuyet** [comment]
fixed for me

**Comment by ptomasroos** [comment]
I'm currently at vacation. Will check back when being home again to see if I can find the cause.

**Comment by devanshsadhotra** [comment]
@vokhuyet  this was solved and then apparently more issues appeared

**Comment by vokhuyet** [comment]
What issue did you get ? @devanshsadhotra

**Comment by vokhuyet** [comment]
I can try to pass navigation prop to child view. Sorry my english is so bad .

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
