### ISSUE TITLE
ScrollView inside SceneContainer: scroll sometimes don't work

### ISSUE THREAD

**Issue by jbarradas** [exponentjs/react-native-tab-navigator#154]
I have a section of the app with RN Tab Navigator, and inside 2 screens, I will basically  have `<TextInput>s` with a `<Button>` at the end.

The problem is: It's been hard to scroll down or up. Sometimes it scroll right away, but normally not. I've seen some issues with ScrollView, needed the `flex: 1` for all `<View>` parents, but I already tried that but no luck..

So I was wondering if it's some problem with this package. Maybe it's not prepared to handle ScrollViews. Also because I see that it has a `<View>` with `position: 'absolute'` and it might influence?

Well, before changing the Tab Navigator and try a new one, I would really like to get a solution for this one. Maybe it's me, failing on something.

I also thought on changing to a `<ListView>` (which I don't see people complaining on the `flex: 1` thing, but honestly, it doesn't seem to be the appropriate component, because it's purpose is to  "repeat" some component with several data. And I don't have that data yet, i'm building some "profile editing" fields.

Thanks in advance for any help! :)

**Comment by ptomasroos** [comment]
We're using ScrollViews inside of it and are not experiencing any problems which you're referring to. Would be great if you could make a reproduction repo example so I can debug it

**Comment by jbarradas** [comment]
The problem seems NOT to be from this package, but in our code. I created a dummy app to test it and it was OK. In few days I will start to debug this issue, and if I find anything relative to this package, I will get back to you ;) Sorry for opening this issue! Cheers and keep up the good work ;)

**Comment by ptomasroos** [comment]
Thanks for the response!

**Comment by ghost** [comment]
@ptomasroos  @jbarradas  Can you please share a small snippet ?

TabNavigator -> ScrollView horizontal -> TabNavigatorItem or wrap it in View ?

**Comment by ptomasroos** [comment]
If you provide me with a example app I can def take a look at it if you don't mind @Amit-Kolambikar ?
