### ISSUE TITLE
I used the react - native - tab - navigator, which was always reported wrong after initialization.

### ISSUE THREAD

**Issue by jiakaiHE** [exponentjs/react-native-tab-navigator#155]
undefined is not  an object(evaluating 'item.props.selected')

**Comment by wzpziyi1** [comment]
I also had such mistakes in the react - native 0.47.1

**Comment by wzpziyi1** [comment]
I solved a problem.Modify the package. Json file 
"react" : "16.0.0 - alpha. 12"

**Comment by ptomasroos** [comment]
Is this still a problem occuring for you @jiakaiHE ?

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
