### ISSUE TITLE
position tab navigator on top

### ISSUE THREAD

**Issue by zanisis** [exponentjs/react-native-tab-navigator#158]
by default on bottom. how i can set for top. because if i set top 0 in the bottom for scene not fully

**Comment by HelenChenVIP** [comment]
How did you solve it?

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.

**Comment by AnkitaKansal** [comment]
How to solve this?

**Comment by AnuragTiwari1** [comment]
+1
