### ISSUE TITLE
This error occurs when I click on navigation components

### ISSUE THREAD

**Issue by TonyTianfei** [exponentjs/react-native-tab-navigator#162]
D:\React-native\CircleAPP\node_modules\react-native\Libraries\Core\ExceptionsManager.js:73 Attempted to transition from state `RESPONDER_INACTIVE_PRESS_IN` to `RESPONDER_ACTIVE_LONG_PRESS_IN`, which is not supported. This is most likely due to `Touchable.longPressDelayTimeout` not being cancelled.

**Comment by TonyTianfei** [comment]
Click too fast, it becomes like this

**Comment by razerduy** [comment]
me too

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
