### ISSUE TITLE
Error while updating property 'nativeBackgroundAndroid' of a view managed by: RCTView

### ISSUE THREAD

**Issue by JevonJ** [exponentjs/react-native-tab-navigator#163]
This error occurs when i'm running the app on a device with API 23 and Android 6.0 
![error](https://user-images.githubusercontent.com/19817313/32156286-6eaeeeae-bd62-11e7-9e2e-19f1d131c5a9.png)

I've found the location of the error. It's in the [Tab.js](https://github.com/happypancake/react-native-tab-navigator/blob/master/Tab.js) file, On the line 71.

`
<TouchableNativeFeedback
      testID={this.props.testID}
      background={TouchableNativeFeedback.Ripple(undefined, true)} // <----- This Line.
      onPress={this._handlePress}>
      <View style={tabStyle}>
        <View>
          {icon}
          {badge}
         </View>
         {title}
        </View>
</TouchableNativeFeedback>
`

It works fine when i remove that perticular line. What is the proper solution for this?

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
