### ISSUE TITLE
It dosen't show the tab-navigator  in my android emulator , how to solve the problem?

### ISSUE THREAD

**Issue by Neowalker69** [exponentjs/react-native-tab-navigator#164]
`import React, { Component } from 'react';
import {
  Platform,
  StyleSheet,
  Text,
  View,
  Image
} from 'react-native';
import TabNavigator from 'react-native-tab-navigator';

export default class App extends Component {
  constructor(props) {
    super(props);
    this.state = {
      selectedTab:'HomePage'
    };
  }
  render() {
    return (
      <View style={styles.container}>
        <View style={styles.topBar}>
          <Text style={styles.instructions}>
            智慧安全用电平台
          </Text>
        </View>
        <TabNavigator>
          <TabNavigator.Item
            // 设置选中的位置
            selected={this.state.selectedTab==='HomePage'}
            // 设置标题
            title='主页'
            // 设置标题样式
            titleStyle={styles.tabText}
            // 设置tab被选中时的样式
            selectedTtileStyle={styles.selectedText}
            //渲染图标
            renderIcon={()=><Image style={styles.icon} source={require('./images/icon/ic_homePage_formal.png')} />}
            renderSelectedIcon={()=><Image style={styles.icon} source={require('./images/icon/ic_homePage_selected.png')} />}
            badgeText="2"
            onPress={()=>this.setState({selectedTab:'HomePage'})}>
            <Text style={styles.welcome}> This text is the HomePage </Text>
          </TabNavigator.Item>
          <TabNavigator.Item
            selected={this.state.selectedTab==='Supervise'}
            title='电气预警'
            titleStyle={styles.tabText}
            selectedTtileStyle={styles.selectedText}
            renderIcon={()=><Image style={styles.icon} source={require('./images/icon/ic_supervise_formal.png')} />}
            renderSelectedIcon={()=><Image style={styles.icon} source={require('./images/icon/ic_supervise_selected.png')} />}
            onPress={()=>this.setState({selectedTab:'Supervise'})}>
            <Text style={styles.welcome}> This text is the Supervise </Text>
          </TabNavigator.Item>
          <TabNavigator.Item
            selected={this.state.selectedTab==='Management'}
            title='末端监控'
            titleStyle={styles.tabText}
            selectedTtileStyle={styles.selectedText}
            renderIcon={()=><Image style={styles.icon} source={require('./images/icon/ic_manage_formal.png')} />}
            renderSelectedIcon={()=><Image style={styles.icon} source={require('./images/icon/ic_manage_selected.png')} />}
            onPress={()=>this.setState({selectedTab:'Management'})}
          >
            <Text style={styles.welcome}> This text is the Management </Text>
          </TabNavigator.Item>
          <TabNavigator.Item
            selected={this.state.selectedTab==='Mine'}
            title='我的'
            titleStyle={styles.tabText}
            selectedTtileStyle={styles.selectedText}
            renderIcon={()=><Image style={styles.icon} source={require('./images/icon/ic_mine_formal.png')} />}
            renderSelectedIcon={()=><Image style={styles.icon} source={require('./images/icon/ic_mine_selected.png')} />}
            onPress={()=>this.setState({selectedTab:'Mine'})}>
            <Text style={styles.welcome}> This text is the Mine </Text>
          </TabNavigator.Item>
        </TabNavigator>
      </View>
    );
  }
}
const styles = StyleSheet.create({
  container: {
    flex: 1,
    // justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#dbdbdb',
  },
  welcome:{
    textAlign:'center',
    color:'#708090'
  },
  instructions: {
    textAlign: 'center',
    color: '#f0f8ff',
    marginTop: 5,
    fontSize:18,
  },
  topBar:{
    width:'100%',
    height:35,
    backgroundColor:'#00bfff',
  },
  tabText:{
    fontSize:10,
    color:'#707070'
  },
  selectedText:{
    fontSize:10,
    color:'#00bfff'
  },
  icon: {
    width: 20,
    height: 20
  }

});
`
This is my demo,but does not work in the android emulator,it doesn't show the tab-navigator and throw any errors as well , how can i work it out? Can someone help me?

**Comment by log4b0at** [comment]
Same problem, UP!

**Comment by yingpengsha** [comment]
Same problem,my react native version is 0.55.4.

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
