### ISSUE TITLE
A simple Tabnavigator demo but there are some errors：Tabnavigator.item is not an object 

### ISSUE THREAD

**Issue by GFWNB** [exponentjs/react-native-tab-navigator#167]
errors detai：

TypeError:undefined is not an object(evaluating '_this.props.Tabnavigator.item')

I just copy the example,there is nothing different but images resource.

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.

**Comment by tlightsky** [comment]
having same problem
