### ISSUE TITLE
How to resolve the delay of 0.5 seconds

### ISSUE THREAD

**Issue by DIVIBEAR** [exponentjs/react-native-tab-navigator#168]
How to resolve the delay of 0.5 seconds?

**Comment by develemit** [comment]
I had a problem with delays too. I realized that I still had few console.logs laying around in my code that triggered every time a tab changed. I took out all the console.logs and it took care of my issue. 

Another thing may also be the remote debugger, that can slow things down a bit. If you build for release it's fast as lightening.

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
