### ISSUE TITLE
Is it possible to change the active color for icons

### ISSUE THREAD

**Issue by solchea** [exponentjs/react-native-tab-navigator#17]
Thanks for implementing this, it's been great so far. I'm wondering how to set the active/inactive colors for icons. For TabBarIOS, there was a tintColor prop. So for the below example, how would I change the icon for the A tab to white instead of blue? Thanks in advance for your help.

![screen shot 2015-10-29 at 8 56 51 am](https://cloud.githubusercontent.com/assets/1445145/10823903/1581b56a-7e1b-11e5-82ad-df95e25ea51d.png)

**Comment by ide** [comment]
The TabItems have a prop called `renderSelectedIcon` -- you could return a white image (use tintColor to help you) from there.

**Comment by solchea** [comment]
Perfect - thanks for your help.
