### ISSUE TITLE
How to add Image different layout ?

### ISSUE THREAD

**Issue by lovebluedan** [exponentjs/react-native-tab-navigator#170]
eg:
At the bottom of the QQ space, there is a different layout in the middle.
I try to do it, but ... At the bottom of  layout  have a some margin  !!

![pic](https://user-images.githubusercontent.com/20750475/34433769-638ffd72-ecbc-11e7-8f91-7c727cb4a334.png)

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
