### ISSUE TITLE
Vertical white lines between tabbar buttons

### ISSUE THREAD

**Issue by ghost** [exponentjs/react-native-tab-navigator#174]
Hi!

Our team found an issue with vertical white lines as shown on the picture below. It happens only on big displays such as iPhone 7 plus. On small screens such as iPhone 5s, iPhone 7 no lines are displayed.
<img width="353" alt="tabbar issue" src="https://user-images.githubusercontent.com/21170342/36103089-a474a9c6-100e-11e8-9fd6-d3b4506cd595.png">

I've tried to debug styles both in the app and in the library code and no clue where those lines are coming from.

Would be awesome to understand how to fix this :)

**Comment by karimbutt** [comment]
+1 having the same issue here

**Comment by andresteves** [comment]
@maksim-harakhovich-itechart @karimbutt  Is it me or only happens after every two items?

**Comment by karimbutt** [comment]
@andresteves yea, seems to happen every 2 items for me

**Comment by TuKDoan** [comment]
<img width="333" alt="screen shot 2018-03-10 at 3 19 47 pm" src="https://user-images.githubusercontent.com/32083324/37246839-8d5819cc-2476-11e8-8717-567f6ec415c0.png">
<img width="335" alt="screen shot 2018-03-10 at 3 19 56 pm" src="https://user-images.githubusercontent.com/32083324/37246840-8d6b2ddc-2476-11e8-8a75-957a9de05cd3.png">
<img width="325" alt="screen shot 2018-03-10 at 3 19 59 pm" src="https://user-images.githubusercontent.com/32083324/37246841-8d7d6380-2476-11e8-95c5-d1dc10513019.png">

I also have this problem

**Comment by ptomasroos** [comment]
If someone could provide me with a running working example I could take a look at fixing this

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.

**Comment by karimbutt** [comment]
@ptomasroos it happens on larger sized screens like iPhone 7 or 8 Plus for me but works fine on smaller screens. We have an app in production that has this issue - are you looking to just see the issue (i.e., I can give you creds to check it out) or are you looking for the code (in which case I can send you snippets rather than the whole repo)?

**Comment by ptomasroos** [comment]
I prefer a expo repo I can reproduce it on! Would love to help out if I can reproduce it. Please open a new issue
