### ISSUE TITLE
How do i use ScrollView to have a horizontal scrolling tabs ?

### ISSUE THREAD

**Issue by ghost** [exponentjs/react-native-tab-navigator#178]
I am trying to do this - [https://youtu.be/6sGhDYYUoBM?t=23s](https://youtu.be/6sGhDYYUoBM?t=23s)

`
  <ScrollView horizontal={true}>
        <TabNavigator style={styles.container}
        tabBarStyle={styles.tabBarStyle}>
          <TabNavigator.Item
            selected={this.state.selectedTab === 'profile'}
            title="Profile"
            selectedTitleStyle={{color: "#3496f0"}}
            tabStyle={styles.tabStyle}
            titleStyle={styles.tabText}
            onPress={() => this.setState({selectedTab: 'profile'})}>
            <Profile/>
          </TabNavigator.Item>
          ... more tab items
        </TabNavigator>
      </ScrollView>`

**Comment by ghost** [comment]
Can someone help me please ?

**Comment by ptomasroos** [comment]
If you can please provide me with a demo repository which is runnable I'm def willing to help out with this!

**Comment by ghost** [comment]
@ptomasroos Here you go https://github.com/Amit-Kolambikar/fc/blob/master/App.js It doess't have much information apart from what I wrote in the post.

**Comment by ghost** [comment]
@ptomasroos This is the expo url - exp://192.168.0.103:19000

**Comment by ghost** [comment]
@ptomasroos Did you have a look ? I tried to add `<View>` but it still doesn't work
