### ISSUE TITLE
How do i enable babel options? 

### ISSUE THREAD

**Issue by BigPun86** [exponentjs/react-native-tab-navigator#18]
Hey there. I didn´t get it how to enable babel options... I am using WebStorm, do i need to enable it in here?

**Comment by ide** [comment]
Create a file called .babelrc in your project root with:

``` json
{
  "whitelist": [
    "es7.decorators",
    "es7.classProperties"
  ]
}
```

It depends on your setup, so if you are doing something custom you may need to configure Babel another way but that's the gist.

**Comment by BigPun86** [comment]
Okay great thanks. But didn´t work for me, and i am not sure how i did setup up babel :P But i´ll find a way...
