### ISSUE TITLE
156:1 Uncaught Error: Module parse failed: Unexpected token (20:19) You may need an appropriate loader to handle this file type. |  | export default class TabNavigator extends React.Component { |   static propTypes = { |     ...ViewPropTypes, |     sceneStyle: ViewPropTypes.style,

### ISSUE THREAD

**Issue by Funny-dot** [exponentjs/react-native-tab-navigator#184]
156:1 Uncaught Error: Module parse failed: Unexpected token (20:19)
You may need an appropriate loader to handle this file type.
| 
| export default class TabNavigator extends React.Component {
|   static propTypes = {
|     ...ViewPropTypes,
|     sceneStyle: ViewPropTypes.style,

**Comment by ptomasroos** [comment]
hi there!

please open a new issue with source code to it, its impossible to guess what could be wrong in your short example.
