### ISSUE TITLE
ReadMe UPDATE ? 

### ISSUE THREAD

**Issue by halloulpsx** [exponentjs/react-native-tab-navigator#20]
Hey could you update the readme file with like how to install and compile using babel ? it is not that clear 

thx

**Comment by jadsonlourenco** [comment]
Yes don't have the installation on Readme, but is `npm i react-native-tab-navigator --save`, also has other issue about documentation that @ide need help https://github.com/exponentjs/react-native-tab-navigator/issues/19

I can help with this but I don't know the rules for that, if will be like Gitbooks or only on Readme, don't know.

**Comment by ide** [comment]
Create a file called .babelrc in your project root with this:

``` json
{
  "whitelist": [
    "es7.classProperties",
    "es7.decorators"
  ]
}
```

This will break in a couple of weeks with RN 0.16, which will move to Babel 6 though.

**Comment by timzaak** [comment]
if there any help to build with the lastest maste branch?
I build with 
babel-plugin-transform-decorators  and
babel-plugin-transform-class-properties,
but it goes wrong with my other code.

**Comment by timzaak** [comment]
transform-class-properties  has bug https://github.com/babel/babel/issues/2983
