### ISSUE TITLE
how to set the text's fontsize in the tabbar?

### ISSUE THREAD

**Issue by YComputer** [exponentjs/react-native-tab-navigator#21]
how to set the text's fontsize in the tabbar?

**Comment by ide** [comment]
TabItems have a prop called titleStyle: https://github.com/exponentjs/react-native-tab-navigator/blob/e837d9d52fa299ad36945e785f47473027bb9017/TabNavigator.js#L116

**Comment by Hy-M** [comment]
Hello,
like so: 

	<Tab.Navigator
				tabBarOptions={{
					activeTintColor: "#50d3a7",
					inactiveTintColor: "gray",
					labelStyle: {
						fontSize: 15,
					},
				}}
			>

**Comment by edkim3275** [comment]
you can also try this way:

```
<Tab.Screen name="tabName" component={componentName} options={{
    tabBarLabelStyle: {
        fontSize: 12,
        fontWeight: "bold",
    }
}} />
```
