### ISSUE TITLE
Can i put these tabs on Top?

### ISSUE THREAD

**Issue by BigPun86** [exponentjs/react-native-tab-navigator#22]
Like Title says, i am trying to use this module as topBar Tabs for my Android Application. Tried several Navigator Tabs in the past, 'react-native-scrollable-tab-view' was actually my favourite, but there seems to be a lot of issues especially after updating my RN to 0.15

**Comment by ide** [comment]
Interesting idea - I think you could do this with the tabBarStyle prop (and tabBarShadowStyle prop to move the thin shadow down). It won't integrate nicely with a Navigation Bar but if you simply want tabs at the top it should be simply a matter of styling.

**Comment by shohey1226** [comment]
As per android style guideline, tab should be top. And I used the below. (I'm using Navigator. If not, `top` may be 0)

```
<TabNavigator tabBarStyle={{top:56,}} tabBarShadowStyle={{bottom:0, top: null}} style={{paddingBottom:-50}}>
```

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
