### ISSUE TITLE
Styling tab item possible?

### ISSUE THREAD

**Issue by kinhunt** [exponentjs/react-native-tab-navigator#24]
I would like to giving different styles (ie, backgroundColor) to each tab container, even different style depends on selected or not. is it possible?

**Comment by ide** [comment]
You can render any view you want with `renderIcon` and `renderSelectedIcon`... does that work for you?

**Comment by kinhunt** [comment]
renderIcon and renderSelectedIcon are very useful. It would be even more flexible if the tab container style can be customized.

In Tab.js, line 43

```
    let tabStyle = [styles.container, title ? null : styles.untitledContainer];
```

**Comment by magrinj** [comment]
I add this option in my PR #61

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
