### ISSUE TITLE
RN 0.16 Support

### ISSUE THREAD

**Issue by lucasterra** [exponentjs/react-native-tab-navigator#27]
I see you added RN 0.16 support for your `@exponent/react-native-navigator` component (thanks for that, btw).
Will you also add support for `react-native-tab-navigator`?

Thanks!

**Comment by lucasterra** [comment]
I did the autobind tricks and now it works just fine. I can open a PR if you want.

**Comment by ide** [comment]
A PR would be appreciated.

**Comment by kinhunt** [comment]
+1

**Comment by ide** [comment]
Thanks for the PR =)

0.2.13 is now on npm.
