### ISSUE TITLE
React.createElement type should not be null.

### ISSUE THREAD

**Issue by teaegg** [exponentjs/react-native-tab-navigator#30]
I got a warning: React.createElement type should not be null. And, tab-navigator could not display
after updated to RN 0.16 and react-native-tab-navigator@0.2.13   on Android.

**Comment by teaegg** [comment]
A babel issue.

Replace

``` javascript
export default class TabNavigator extends React.Component {
    ...
}
```

With ->

``` javascript
module.exports = TabNavigator;
class TabNavigator extends React.Component {
    ...
}
```

done.

**Comment by timzaak** [comment]
if you use `require('react-native-tab-navigator')` to import this. please change to import  XX from 'react-native-tab-navigator'
This helps me.

**Comment by teaegg** [comment]
thanks, it works well.

**Comment by ide** [comment]
With RN 0.16 you should use ES6 modules (import / export) instead of CommonJS (require / module.exports).
