### ISSUE TITLE
wired problem after update to react native 0.16

### ISSUE THREAD

**Issue by sospartan** [exponentjs/react-native-tab-navigator#31]
I got an error with latest tab navigator and react native 0.16:  
![screen shot 2015-12-07 at 7 54 18 pm](https://cloud.githubusercontent.com/assets/115201/11626260/637c2dd4-9d1c-11e5-8afc-baa15d38e7f2.png)  
My code:  

``` jsx
var TabBar = Platform.OS === 'ios'?React.TabBarIOS:require('react-native-tab-navigator');
var TabNavigator = React.createClass({
  getInitialState: function() {
    return {
      selectedIndex: 0,
    };
  },
    _isCurrentTab:function(index){
        //console.log(""+this.state.selectedIndex+"==="+index);
        return this.state.selectedIndex===index;
    },
  render: function() {
      //... tabs is just a array of <TabBar.Item/>

      return (
          <TabBar style={{backgroundColor:'black'}}>
              {tabs}
          </TabBar>
      );
  },
});
```

Nothing special . I think.
After some hours for searching reason. I found a work around:  
in 'TabNavigator.js' , remove `export default` and use `module.exports = TabNavigator;` to export the module .
I'm a js newbie , not sure it's a js or react native problem , or just related to this module.

**Comment by timzaak** [comment]
#30 this will help you

**Comment by ide** [comment]
Thanks @timzaak.

Use ES6 `import` instead of CommonJS `require`. I'll add this to the README for clarity.

**Comment by sospartan** [comment]
Thanks @timzaak .
