### ISSUE TITLE
 renderIcon doesn't work 

### ISSUE THREAD

**Issue by amibition521** [exponentjs/react-native-tab-navigator#36]
renderIcon={() => <Image source={require('image!home')} style = {styles.size}/>}
renderSelectedIcon={() => <Image source={require('image!home')} style = {styles.size}/>}
![20151219202518](https://cloud.githubusercontent.com/assets/13275317/11913255/47ec0b3a-a699-11e5-9a3d-2e8aa3b8afac.png)

**Comment by amibition521** [comment]
renderIcon={() => <Image source={require('image!ic_collected_white')} style = {styles.size}/>}
renderSelectedIcon={() => <Image source={require('image!ic_collect_white')} style = {styles.size}/>}

**Comment by amibition521** [comment]
renderIcon = {Image source={require ('image!ic_collected_white')}}
renderSelectedIcon = {Image source={require('image!ic_collect_white')}}

**Comment by ide** [comment]
Can you verify that your icon `<Image>` components show up when you use them outside of the TabNavigator?

**Comment by amibition521** [comment]
TabNavigator  Are there any requirements for image size?

**Comment by ide** [comment]
You should make them about 22x22 big but it doesn't need to be exact. You can also put some margin/padding on them to adjust their positions.

**Comment by amibition521** [comment]
Thanks
