### ISSUE TITLE
Animate the tab changes

### ISSUE THREAD

**Issue by reactor81** [exponentjs/react-native-tab-navigator#37]
Where might I look if I want to modify this code to animate the tab changes. I dont want side scrolling that scrollable tab view has, i like touching the tabs only. But, I 'd like to animate / smooth transition instead of the instant transition now. 

How might this be possible?

(i know scrollable tab view can lock, still, I prefer to use this package - react native tab navigator).

**Comment by ide** [comment]
This isn't supported by TabNavigator. You could fork it and try to get it working -- you'd want to look at TabNavigator's render method. That said, the way the scenes were set up it's probably not very easy to make them scroll.

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
