### ISSUE TITLE
Babel 6.4.x failure

### ISSUE THREAD

**Issue by ben-manes** [exponentjs/react-native-tab-navigator#40]
> react-native-tab-navigator/TabBar.js. A semicolon is required after a class property

Easy fix, just add the semicolon after the propTypes.

**Comment by ide** [comment]
Thanks for the heads up. Could you try getting 0.2.15 from npm?

**Comment by ben-manes** [comment]
We have a fork for some reason, so I applied the same fix and pushed there when testing the react-native issue. That works for me, so you should be able to close this now.

**Comment by ide** [comment]
Great, thank you for testing.
