### ISSUE TITLE
why this error?

### ISSUE THREAD

**Issue by yuanguozheng** [exponentjs/react-native-tab-navigator#41]
![image](https://cloud.githubusercontent.com/assets/6261504/12191450/0d7b7b26-b610-11e5-952c-1a0e08d34140.png)
onlyChild must be passed a children with exactly one child.

**Comment by yuanguozheng** [comment]
when i set TabNavigator.Item's selected to true

**Comment by ide** [comment]
You're trying to render 0 or > 1 child in a component that wants one child as the error states. You should debug further.

**Comment by yuanguozheng** [comment]
Thanks! The problem has been solved! I didn't add any child…………
╮（╯＿╰）╭
