### ISSUE TITLE
Unable to resolve module immutable

### ISSUE THREAD

**Issue by KBLNY** [exponentjs/react-native-tab-navigator#42]
Hi, 
Thanks for the code, it looks like really awesome.
However, I installed it via the npm command, as you suggest.
But I get the following error:
Unable to resolve module immutable from /<My Project Path>/node_modules/react-native-tab-navigator/TabNavigator.js: Invalid directory /Users/node_modules/immutable
Even, after installing "immutable" with npm.
Any idea ?
Thanks

**Comment by ide** [comment]
immutable is specified under package.json so I'm not sure what TabNavigator can do. Sounds like an operational issue on your end. Try restarting your packager, computer, clearing caches, etc.
