### ISSUE TITLE
How should the initialTab be set

### ISSUE THREAD

**Issue by BigPun86** [exponentjs/react-native-tab-navigator#44]
Hey there.

In my Tab Component i set the initialTab in my getInitialState as follows: 

```
getStateFromStore: function () {
    return {
        selectedTab: 'tab1'
    }
},
```

I use two Tabs with the TabNavigator, the problem i have now, is that when i set it initial to tab1 it jumps "sometimes" from tab2 to tab1. I tried setting nothing because i thought it might be handles in the react-native-tab-navigator component.
Actually i hope someone can show me their solution i just coudn´t figure out how to set the initial selectedTab so there is no jumping around

My TabNavigators:

```
      <TabNavigator
            tabBarStyle={{padding: 10, backgroundColor: `white`, height: tabBarHeight, top:0, borderBottomWidth: 0.5, borderBottomColor: `grey`}}
            sceneStyle={{ backgroundColor: 'red', paddingBottom: tabBarHeight }}>
            <TabNavigator.Item
                selected={this.state.selectedTab === 'tab1'}
                title={"TAB1"}
                titleStyle={{fontSize: 16, fontWeight: 'bold'}}
                onPress={() => this.setState({ selectedTab: 'tab1' })}>
                <View style={{flex: 1, marginTop: marginTop}}>
                    <Tab1Screen
                        {...this.props}/>
                </View>
            </TabNavigator.Item>
            <TabNavigator.Item
                selected={this.state.selectedTab === 'tab2'}
                title={"TAB2"}
                titleStyle={{fontSize: 16, fontWeight: 'bold'}}
                onPress={() => this.setState({ selectedTab: 'tab2' })}>
                <View style={{flex: 1, marginTop: marginTop}}>
                    <Tab2Screen
                        {...this.props}/>
                </View>
            </TabNavigator.Item>
        </TabNavigator>
```

**Comment by ide** [comment]
I think your problem is that `this.state.selectedTab` might be null or an invalid value at some point. Try initializing your component with `this.state = { selectedTab: 'tab1' }`.

**Comment by BigPun86** [comment]
Okay, i will try it. But isn´t it just a different syntax when using class React.Component instead of var React.createClass:

```
constructor(){
    super();
    this.state = {
        selectedTab: 'tab1'
    }
}
```

VS

```
getInitialState(){
    return {
        selectedTab: 'tab1'
    }
}
```

Shoudn´t this give me the same result?

**Comment by ide** [comment]
getInitialState should be fine too. I just don't know if getStateFromStore is causing issues for you.

**Comment by BigPun86** [comment]
Oh man! I am an idiot :D i forgot to change that :D I´ll try it later, thanks...

**Comment by BigPun86** [comment]
Okay thanks! The issue was caused by my Store....
