### ISSUE TITLE
Support Animated

### ISSUE THREAD

**Issue by grabbou** [exponentjs/react-native-tab-navigator#45]
Would be cool to control `TabBar` appearance with Animated, so that I can animate it in / out. Unfortunately, LayoutAnimation does not work in my case, since there are quite a few other things going on onscreen. 

Imo just a matter of replacing https://github.com/exponentjs/react-native-tab-navigator/blob/master/TabBar.js#L19 with Animated.View. I am happy to pass animation style via `tabBarStyle` property.

**Comment by 9mm** [comment]
:+1:

**Comment by ide** [comment]
Sounds good -- can you send a PR? Normally Animated is pretty expensive to have on the screen (replacing TouchableX with plain Views speeds things up) but there's only one TabBar per app most of the time so I think this is fine.
