### ISSUE TITLE
Right way to style the badge?

### ISSUE THREAD

**Issue by CodingSam** [exponentjs/react-native-tab-navigator#46]
The way I am now doing this now is:

Import the Badge module
`import Badge from './node_modules/react-native-tab-navigator/Badge';`

In the TabNavigator.Item I add it int the renderBadge function like this:
`<TabNavigator.Item
  renderBadge={() => <Badge style={styles.tabBarBadge}>1</Badge>}
</TabNavigator.Item>`

Would it be possible to expose the Badge in the TabNavigator? Like the TabNavigator.Item

**Comment by dovfrank** [comment]
I'm doing the same...

**Comment by ide** [comment]
The default badge is something we don't want to expose as a public API. If you like the way it looks, I recommend you copy & paste the code.

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
