### ISSUE TITLE
Android - Tab bar does not show

### ISSUE THREAD

**Issue by manpreetmanur** [exponentjs/react-native-tab-navigator#51]
Andriod: Tab bar content does not show if we don't specify the height of the container. It comes up only if we give a height to scroll view in case of android.

I cannot specify the height of the scrollabletab view as it can have the dynamic content. 

IOS: Another issue is if the height of the second page is more than the first one, then the first page also takes the same height.

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
