### ISSUE TITLE
for android ,tabbar can't hide

### ISSUE THREAD

**Issue by moxiaobei2** [exponentjs/react-native-tab-navigator#52]
when i used route for change activity,I can go to another activity,but tabbar is still showed.How I can hide the bar,how Can I do in the child activity?

**Comment by dovfrank** [comment]
+1

**Comment by zubricky** [comment]
Android doesn't support the style overflow: hidden. You could just move the tab bar off the screen.

``` js
var Dimensions = require('Dimensions');

if (hidden) {
    var tabBarStyle = {position: 'absolute', top: Dimensions.get('window').height};
    var sceneStyle = {paddingBottom: 0};
} else {
    let tabBarHeight = 50;
    var tabBarStyle = {height: tabBarHeight};
    var sceneStyle = {paddingBottom: tabBarHeight};
}

<TabNavigator
    tabBarStyle={tabBarStyle}
    sceneStyle={sceneStyle}
/>
```

**Comment by moxiaobei2** [comment]
@zubricky thank you.

**Comment by toearth** [comment]
@zubricky Thanks +1

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
