### ISSUE TITLE
Support Icon Fonts - iconType option

### ISSUE THREAD

**Issue by gfranko** [exponentjs/react-native-tab-navigator#55]
Currently, it is assumed that an **Image** component is used for the icon, and will throw a warning if a different component is used (since the **tintColor** style is not supported for other types of components).  

Since icon fonts are also widely used, would you be open to creating a new `iconType` option that allowed you to specify `text` or `image` (the default), and would only add the default **tintColor** style if the type was an image?

Thanks again for all your hard work

**Comment by alfonsodev** [comment]
I've been using [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons/) they support TabBarIOS by kind of [patching TabBarIOS.Item](https://github.com/oblador/react-native-vector-icons/blob/abcdfd39bbb7b8e2f0d7cc175b0cfa9e7947d967/lib/create-icon-set.js#L203)  The key is the function `getImageSource` by using it you should be able to get a valid image, I'll be trying to make both modules work together, I'll keep this issue updated.

**Comment by alfonsodev** [comment]
by using [react-native-vector-icons](https://github.com/oblador/react-native-vector-icons)
you can pass <Icon /> component to the renderIcon prop.
```js
      var Icon = require('react-native-vector-icons/FontAwesome')

        <TabNavigator>
          <TabNavigator.Item
            selected={this.state.selectedTab === 'home'}
            renderIcon={() => <Icon name="home" size={30} color="#900" /> }
             title = "home"
            iconSize={28}
            >
            <View style={{paddingTop: 100}}></View>
          </TabNavigator.Item>
        </TabNavigator>
```

**Comment by magrinj** [comment]
#61

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
