### ISSUE TITLE
install on mac is ok,but on windows is error

### ISSUE THREAD

**Issue by xpmike** [exponentjs/react-native-tab-navigator#56]
D:\workspace\react-native-work\MyApp>npm install react-native-tab-navigator --save
npm WARN install:nan@2.2.0 EPERM: operation not permitted, rename 'D:\workspace\react-native-work\MyApp\node_modules.staging\nan-9eada15a' ->'D:\workspace\react-native-work\MyApp\node_modules\nan'MyApp@0.0.1 D:\workspace\react-native-work\MyApp+-- bindings@1.2.1  extraneous`-- react-native-tab-navigator@0.2.17

npm WARN optional Skipping failed optional dependency /chokidar/fsevents:
npm WARN notsup Not compatible with your operating system or architecture: fseve
nts@1.0.8

**Comment by ide** [comment]
That's a warning, not an error. And I believe it's unrelated to this package.
