### ISSUE TITLE
TextInput lose focus.

### ISSUE THREAD

**Issue by amibition521** [exponentjs/react-native-tab-navigator#58]
One page has a TextInput component.I want to let it loses focus, at the time of page switching, have what way?

**Comment by ide** [comment]
We don't have an automatic solution for this. When the user taps a tab and we call the `onPress` function, that's when you have to blur the current TextInput manually.

**Comment by ptomasroos** [comment]
In onPress 

```
  const field = TextInput.State.currentlyFocusedField();
  TextInput.State.blurTextInput(field);
```
