### ISSUE TITLE
In the child component ,the navigator not work

### ISSUE THREAD

**Issue by zhaohysjdd** [exponentjs/react-native-tab-navigator#59]
In my project , I want to use function of navigator in child component of Tabnavigator such as navigator.push.but it`s does`t work.

`_renderTabItem(img,selectedImg, tag, childView) {

```
    return (           

        <TabNavigator.Item
            selected={this.state.selectedTab === tag}
            renderIcon={() => <Image style={styles.tabIcon} source={img}/>}
            renderSelectedIcon={() => <Image style={styles.tabIcon} source={selectedImg}/>}
            onPress={() => this.setState({ selectedTab: tag })}>
            {childView}
        </TabNavigator.Item>            
    );
}`
```

`<TabNavigator hidesTabTouch={false} tabBarStyle={tabBarStyle}  sceneStyle={sceneStyle}>
                    {this._renderTabItem(HOME_NORMAL, HOME_FOCUS, HOME, <ListPage/>)}` 
I want in <ListPage/> use pop and push etc.error is **undefined is not a function (evaluating 'this.props.nav.push({id:name})')**

**Comment by juanq123** [comment]
wo meet the same problem

**Comment by sbaar** [comment]
This is indeed a problem, also arising with navigator.geolocation. I mitigated the problem by moving the navigator.geolocation to the same file as the tab navigator, and passing the results as props to the tabs.

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
