### ISSUE TITLE
style padding error

### ISSUE THREAD

**Issue by duduzai** [exponentjs/react-native-tab-navigator#65]
if we don't set props 'title',tabs still set paddingBottom.I found the answer in line 50 of Tab.js ,should changet  `let tabStyle = [styles.container, title ? null : styles.untitledContainer];` to `let tabStyle = [styles.container, title === undefined ? null : styles.untitledContainer];`

**Comment by magrinj** [comment]
I remove it in my PR  #61

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
