### ISSUE TITLE
Long lists optmise tab switching

### ISSUE THREAD

**Issue by wieseljonas** [exponentjs/react-native-tab-navigator#66]
I was wondering if anyone had manage to optimise tab switching when displaying long lists.

I'm having difficulty doing this I get a significant lag. I'm sure the issue is linked to the listview component and it's problems with long lists. I was wondering though if there was a way to somehow keep each tab in memory to improve this.

Thanks

**Comment by toearth** [comment]
@wieseljonas you can set initialListSize and pageSize of the liseView

**Comment by ptomasroos** [comment]
This is not related to react-native-tab-navigator
