### ISSUE TITLE
help....my navigator disappeared when I used new component in item...

### ISSUE THREAD

**Issue by cristal000o** [exponentjs/react-native-tab-navigator#69]
hi
here is my problem,I set a <HomeTab> in the tabnavigator.Item,,but only the HomeTab showed, the navigator disappaered....the codes are following:
HomeTab:

![image](https://cloud.githubusercontent.com/assets/18301359/14912558/a79660dc-0e2f-11e6-8099-9f0e52dbc120.png)

![image](https://cloud.githubusercontent.com/assets/18301359/14912566/b19c2300-0e2f-11e6-96af-0741b43c042c.png)

![image](https://cloud.githubusercontent.com/assets/18301359/14912399/95b9361a-0e2e-11e6-8c7b-7920a41ec6e1.png)

![image](https://cloud.githubusercontent.com/assets/18301359/14912405/aa02ce60-0e2e-11e6-9d25-b312e3e239ca.png)

**Comment by cristal000o** [comment]
the warning is also annoying...anyone knows how to get rid of it?

**Comment by amzfcy** [comment]
@cristal000o  你这个警告说的是你样式写错了。。。和你这个问题没关系啊，而且你的问题说实话我没看懂，你最好贴个全一点的代码上来

**Comment by Neowalker69** [comment]
I write codes correctly and android emulator doesn't push any errors,but it never show up on the emulator,making me confused!

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
