### ISSUE TITLE
how to hide the tab navigation

### ISSUE THREAD

**Issue by youxikaifa** [exponentjs/react-native-tab-navigator#80]
if i want hide this tab navigation ,how can i do

**Comment by jinghun1999** [comment]
so i'm in the same trobble. how can i hide the bar in the sub page?

**Comment by toearth** [comment]
Hiding the Tab Bar

You can hide the tab bar by using styles. For example:

let tabBarHeight = 0;

```
<TabNavigator
  tabBarStyle={{ height: tabBarHeight, overflow: 'hidden' }}
  sceneStyle={{ paddingBottom: tabBarHeight }}
/>
```

This only works in IOS. It doesn't work in android.

**Comment by byk04712** [comment]
I'm in the same trobble. How can i hide the `TabNavigator` in the sub page, Does anynoe can help us?
 Thanks.

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
