### ISSUE TITLE
Need Help:Super expression must either be null or a function.not undefined..

### ISSUE THREAD

**Issue by lj694580957** [exponentjs/react-native-tab-navigator#83]
Hi,friend.
i have install your packages.but it show the wrong:
`Super expression must either be null or a function.not undefined..
inherits
babelHelpers.js:114:0
unknown
Badge.js:11:0
unknown
Badge.js:57:0
loadModuleImplementation
require.js:100:0
...`

myindex.android.js :
`'use strict';
import React, { Component } from 'react';
import {
    AppRegistry,
    StyleSheet,
    Image,
    Text,
    View,
    Navigator
} from 'react-native';
import TabNavigator from 'react-native-tab-navigator';
class  AwesomeProject extends React.Component{
    constructor(props) {
        super(props);
        this.state = {selectedTab: 'home'}
    }

```
render(){
    return (
        <View style={{flex:1}}>
            <TabNavigator
            />
        </View>
    );
}
```

}
AppRegistry.registerComponent('AwesomeProject', () => AwesomeProject);` 

package.json:
{
  "name": "AwesomeProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "start": "node node_modules/react-native/local-cli/cli.js start"
  },
  "dependencies": {
    "i": "^0.3.5",
    "react": "^15.0.2",
    "react-native": "^0.26.1",
    "react-native-tab-navigator": "^0.2.15",
    "react-native-viewpager": "^0.2.1",
    "realm": "^0.13.2",
  }
}

when i annotate "import TabNavigator from 'react-native-tab-navigator'; " is right.
so help me .

![Uploading log.JPG…]()

**Comment by spezzino** [comment]
The plugin is working under this dependencies

"dependencies": {
    "react": "^15.1.0",
    "react-native": "0.27.2",
    "react-native-tab-navigator": "^0.3.2"
  }

Maybe you should update react-native and the plugin

**Comment by ptomasroos** [comment]
Will close since this issue is more than a year, feel free to a open a new if this is still a issue.
