### ISSUE TITLE
Install error.

### ISSUE THREAD

**Issue by leeggco** [exponentjs/react-native-tab-navigator#92]
First, Thx for the code.

> F:\york\ReactNative\BujuPorject>npm install react-native-tab-navigator --save
> 
> > bufferutil@1.2.1 install F:\york\ReactNative\BujuPorject\node_modules\bufferutil
> > node-gyp rebuild
> 
> F:\york\ReactNative\BujuPorject\node_modules\bufferutil>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: D:\Python27\python.EXE -c import platform; print(platform.python_version());
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:207:12)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
> gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
> gyp ERR! stack     at emitOne (events.js:96:13)
> gyp ERR! stack     at Socket.emit (events.js:188:7)
> gyp ERR! stack     at Pipe._handle.close [as _onclose](net.js:492:12)
> gyp ERR! System Windows_NT 10.0.10586
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd F:\york\ReactNative\BujuPorject\node_modules\bufferutil
> gyp ERR! node -v v6.2.2
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> npm WARN install:bufferutil@1.2.1 bufferutil@1.2.1 install: `node-gyp rebuild`
> npm WARN install:bufferutil@1.2.1 Exit status 1
> 
> > utf-8-validate@1.2.1 install F:\york\ReactNative\BujuPorject\node_modules\utf-8-validate
> > node-gyp rebuild
> 
> F:\york\ReactNative\BujuPorject\node_modules\utf-8-validate>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "" rebuild )
> gyp ERR! configure error
> gyp ERR! stack Error: Command failed: D:\Python27\python.EXE -c import platform; print(platform.python_version());
> gyp ERR! stack
> gyp ERR! stack     at ChildProcess.exithandler (child_process.js:207:12)
> gyp ERR! stack     at emitTwo (events.js:106:13)
> gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
> gyp ERR! stack     at maybeClose (internal/child_process.js:852:16)
> gyp ERR! stack     at Socket.<anonymous> (internal/child_process.js:323:11)
> gyp ERR! stack     at emitOne (events.js:96:13)
> gyp ERR! stack     at Socket.emit (events.js:188:7)
> gyp ERR! stack     at Pipe._handle.close [as _onclose](net.js:492:12)
> gyp ERR! System Windows_NT 10.0.10586
> gyp ERR! command "C:\Program Files\nodejs\node.exe" "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" "rebuild"
> gyp ERR! cwd F:\york\ReactNative\BujuPorject\node_modules\utf-8-validate
> gyp ERR! node -v v6.2.2
> gyp ERR! node-gyp -v v3.3.1
> gyp ERR! not ok
> npm WARN install:utf-8-validate@1.2.1 utf-8-validate@1.2.1 install: `node-gyp rebuild`
> npm WARN install:utf-8-validate@1.2.1 Exit status 1

What's problem ?

**Comment by ide** [comment]
`utf-8-validate` is not related to this component. There is some issue with the compiler on your machine.
