### ISSUE TITLE
Slide to the right，the tab will wipe up。

### ISSUE THREAD

**Issue by luoshuai5** [exponentjs/react-native-tab-navigator#96]
Slide to the right，the tab will wipe up。

**Comment by luoshuai5** [comment]
![device-201_clip](https://cloud.githubusercontent.com/assets/14367744/17878939/f369a7de-6920-11e6-85d7-b240c05a50af.gif)

**Comment by ide** [comment]
I've never seen this before. Perhaps you're running a non-standard version of Android?
