### ISSUE TITLE
Toggle tabs with Animated/Animation ?

### ISSUE THREAD

**Issue by song50119** [exponentjs/react-native-tab-navigator#98]
Hi, I've tried to  add Animated.TabNavigator but not work?
Is something wrong?
I want to make animation when tabs hide or show.

**Comment by ide** [comment]
TabBar animation is not supported. If you try to create Animated.TabNavigator, it will only add support for Animated styles to a wrapper View, which doesn't help. I recommend you spend some time reading the code in ExNavigation (https://github.com/exponentjs/ex-navigation/tree/master/src/sliding-tab) and using that navigator instead.

**Comment by song50119** [comment]
Thanks
