### ISSUE TITLE
Example with gifs

### ISSUE THREAD

**Issue by waleedarshad-vf** [exponentjs/react-native-tab-navigator#99]

**Comment by woody-worakorn** [comment]
+1

**Comment by brunolemos** [comment]
That's a must have on every project ui-related. Unbelievable.

**Comment by ide** [comment]
Want to send a PR?

**Comment by ptomasroos** [comment]
I see no reason why this should exist, gif's work out of the box in RN with a small addition to adding the fresco dependency
